# Generated by Django 5.1.6 on 2025-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Mindmaps',
            field=models.ManyToManyField(blank=True, related_name='documents', to='members.mindmap'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(blank=True, to='members.member'),
        ),
    ]
